back_end/abonements/urls.py
from django.urls import path
from . import views
from .views import AddProductView, DeleteProductView, UpdateProductView

app_name = 'abonements'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'
         ),
    path('<int:id>/<slug:slug>', views.product_detail,
         name='product_detail'),
    path('abonements/create/', AddProductView.as_view(), name='create'),
    path('home/<slug:pk>/delete', DeleteProductView.as_view(), name='delete'),
    path('home/update/<slug:pk>/', UpdateProductView.as_view(), name='update'),
]

back_end/back_end/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('abonements/', include('abonements.urls', namespace='abonements'))
]+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

back_end/main/urls.py
from django.conf import settings
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path('', views.index , name='home'),
    path('about/', views.about, name='about'),
    path('classes/', views.classes,name='classes'),
    path('schedules/', views.schedules,name='schedules'),
    path('contactus/', views.contactus, name='contactus'),
    path('signup/', views.signup, name='signup'),
    path('register/', views.register, name='register'),
    path('logout/', LogoutView.as_view(),{'next_page': settings.LOGOUT_REDIRECT_URL},name='logout'),

]

back_end/abonements/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse('abonements:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    level = models.CharField('level', max_length=50, db_index=True)
    type = models.CharField('type', max_length=50, db_index=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    slug = models.SlugField(max_length=150, db_index=True, unique=True)
    available = models.BooleanField(default=True)

    class Meta:
        ordering = ('type',)
        verbose_name = 'Product'
        verbose_name_plural = 'Products'
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.type

    def get_absolute_url(self):
        return reverse('abonements:product_detail', args=[self.id, self.slug])

class buy(models.Model):
    name = models.CharField('name', max_length=50, db_index=True)
    number = models.CharField('number', max_length=250)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'buyer'
        verbose_name_plural = 'buyers'

back_end/abonements/forms.py
from django.forms import ModelForm, TextInput

from .models import  buy


class buy(ModelForm):
    class Meta:
        model = buy
        fields = ['name', 'number']
        widgets = {
            'name': TextInput(attrs={
                'placeholder': "Your Name*",

            }),
            'number': TextInput(attrs={
                'placeholder': "Your number*",

            })
        }

back_end/abonements/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, UpdateView

from .models import Category, Product, buy


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'abonements/type_products/price.html',
                  {
                      'category': category,
                      'categories': categories,
                      'products': products
                  })


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    return render(request, 'abonements/type_product/detail.html', {'product': product})

class AddProductView(CreateView):
    model = Product
    template_name = 'abonements/crud/create.html'
    fields = '__all__'
    success_url = reverse_lazy('abonements:product_list')

class DeleteProductView(DeleteView):
    model = Product
    template_name = 'abonements/crud/delete.html'
    success_url = reverse_lazy('abonements:product_list')

class UpdateProductView(UpdateView):
    model = Product
    template_name = 'abonements/crud/update.html'
    fields = '__all__'
    success_url = reverse_lazy('abonements:product_list')


def price(request):
    error = ''
    if request.method == 'POST':
        form = buy(request.POST)
        if form.is_valid():
            form.save()
            return redirect("{% url 'product_list' %}")
        else:
            error = 'ERROR'

    form = buy()

    data = {
        'form': form,
        'error': error
    }
    return render(request, 'abonements/product_list', data)

back_end/abonements/templates/abonements/type_products/detail.html
{% extends "abonements/base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
<div class="product-detail">
<img src="{% if product.image %}{{ product.image.url }}{% else %}
{% static 'img/no_image.png' %}{% endif %}">
<h1>{{ product.name }}</h1>
<h2>
<a href="{{ product.category.get_absolute_url }}">{{product.category }}</a>
</h2>
<p class="price">${{ product.price }}</p>
{{ product.description|linebreaks }}
</div>
{% endblock %}

back_end/abonements/templates/abonements/type_products/price.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap"
          rel="stylesheet">
    <title>Training Studio</title>

    <link rel="stylesheet" href="{% static 'main/css/price.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/bootstrap.min.css' %}">

    <link rel="stylesheet" type="text/css " href="{% static 'main/css/font-awesome.css' %}">

    <link rel="stylesheet" href=" {% static 'main/css/templatemo-training-studio.css '%}">

</head>

<!-- ***** Preloader Start ***** -->
<div id="js-preloader" class="js-preloader">
    <div class="preloader-inner">
        <span class="dot"></span>
        <div class="dots">
            <span></span>
            <span></span>
            <span></span>
        </div>
    </div>
</div>
<!-- ***** Preloader End ***** -->


<!-- ***** Header Area Start ***** -->
<header class="header-area header-sticky">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav class="main-nav">
                    <!-- ***** Logo Start ***** -->
                    <a href="/" class="logo" style="color: black;">Training<em> Studio</em></a>
                    <!-- ***** Logo End ***** -->
                    <!-- ***** Menu Start ***** -->
                    <ul class="nav">
                        <li class="scroll-to-section"><a href="/" style="color: black;">Home</a></li>
                        <li class="scroll-to-section"><a href="/about" style="color: black;">About</a></li>
                        <li class="scroll-to-section"><a href="/classes" style="color: black;">Classes</a></li>
                        <li class="scroll-to-section"><a href="/schedules" style="color: black;">Schedules</a></li>
                        <li class="scroll-to-section"><a href="/contactus" style="color: black;">Contact</a></li>
                        <li class="scroll-to-section"><a href="/price" class="active">Prices</a></li>
                        {% if user.is_authenticated %}
                        <li><a href="{% url 'logout'%}?next={{request.path}}">{{ user.get_username }}/Logout</a></li>
                        {% else %}
                        <li><a class="main-button" href="{% url 'signup'%}?next={{request.path}}">Login</a></li>
                        {% endif %}
                    </ul>
                    <a class='menu-trigger'>
                        <span>Menu</span>
                    </a>
                    <!-- ***** Menu End ***** -->
                </nav>
            </div>
        </div>
    </div>
</header>
<body>
        <div class="row">
            <div class="columns">
                <div id="sidebar" class="ml-3">
                    {% if user.is_authenticated and user.get_username == 'admin' %}
                        <h3>Category/<a href="{% url 'abonements:create' %}">Create Product</a></h3>
                    {% else %}<h3>Category</h3>{% endif %}

                    <div class="btn-group mt-3" role="group">
                        <button class="btn btn-outline-danger" {% if not category %} type="button"   {% endif %}> <a href="{% url 'abonements:product_list' %}">All</a></button>
                        {% for c in categories %}
                            <button class="btn btn-outline-danger" {% if category.slug == c.slug %} type="button" {% endif %}><a
                                    href="{{ c.get_absolute_url }}" style="text-decoration:none">{{ c.name }}</a></button>
                        {% endfor %}
                    </div>
                </div>
                </div>
        </div>
                <div id="main" class="product-list ml-4">
                    <h1>{% if category %}{{ category.name }}{% else %} Product {% endif %}</h1>
                     <div class="rows">
                    {% for product in products %}
                            <div class="columns">
                             <ul class="price ">
                                 <li class="header">{{ product.category.name }}</a></li>
                                <li class="grey">{{ product.level }}</a></li>
                                <li class="white">{{ product.type }}</a></li>
                                <li class="white"> $ {{ product.price }} /month</li>

                            {% if user.is_authenticated and user.get_username == 'admin' %}
                                <a href="{% url 'abonements:update' product.pk %}"><button type="button" class="btn btn-success">Update</button></a>
                                <a href="{% url 'abonements:delete' product.pk %}"><button type="button" class="btn btn-success">Delete</button></a>
                            {% else %}

                               <li style="background-color:#ee5538;"><a href="#"
                                                         onclick="document.getElementById('id03').style.display='block'"
                                                         style="width:auto;color:white ">ACQUIRE</a></li>
                                 </ul>
                                <div id="id03" class="modal">
                                    <div class="contacts d-flex justify-content-center align-items-center">
                                        <div class="col-md-4 p-2 mb-2 bg-white text-dark">
                                            <span onclick="document.getElementById('id03').style.display='none'" class="close"
                                                  title="Close Modal">&times;</span>
                                            <p class="font-weight-bold text-center mb-2 mt-3 text-dark" style="font-size: 22px;">Leave your
                                                contacts below and we will call you</p>
                                            <form method="post">
                                                {% csrf_token %}
                                                <li style="font-size: 24px;" class="font-weight-light">{{form.name}}</li>
                                                <li style="font-size: 24px;" class="font-weight-light">{{form.number}}</li>

                                                <li>
                                                    <button type="submit" id="form-submit" class="text-white font-weight-light "
                                                            style="font-size: 29px; background-color:#ee5538">Call me!
                                                    </button>
                                                </li>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            {% endif %}
                    </div>


                    {% endfor %}
                      </div>
                 </div>



</body>
<script src="{% static 'main/js/jquery-2.1.0.min.js' %}"></script>

<!-- Bootstrap -->
<script src="{% static 'main/js/popper.js' %}"></script>
<script src="{% static 'main/js/bootstrap.min.js' %}"></script>

<!-- Plugins -->
<script src="{% static 'main/js/scrollreveal.min.js' %}"></script>
<script src="{% static 'main/js/waypoints.min.js' %}"></script>
<script src="{% static 'main/js/jquery.counterup.min.js' %}"></script>
<script src="{% static 'main/js/imgfix.min.js' %}"></script>
<script src="{% static 'main/js/mixitup.js' %}"></script>
<script src="{% static 'main/js/accordions.js' %}"></script>

<!-- Global Init -->
<script src="{% static 'main/js/custom.js' %}"></script>
<script>


        var modal = document.getElementById('id03');
        window.onclick = function(event) {
          if (event.target == modal) {
            modal.style.display = "none";
          }
        }

</script>
</html>