back_end/abonements/urls.py
from django.urls import path
from . import views
from .views import AddProductView, DeleteProductView, UpdateProductView

app_name = 'abonements'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'
         ),
    path('<int:id>/<slug:slug>', views.product_detail,
         name='product_detail'),
    path('abonements/create/', AddProductView.as_view(), name='create'),
    path('home/<slug:pk>/delete', DeleteProductView.as_view(), name='delete'),
    path('home/update/<slug:pk>/', UpdateProductView.as_view(), name='update'),
]

back_end/back_end/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('abonements/', include('abonements.urls', namespace='abonements'))
]+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

back_end/main/urls.py
from django.conf import settings
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path('', views.index , name='home'),
    path('about/', views.about, name='about'),
    path('classes/', views.classes,name='classes'),
    path('schedules/', views.schedules,name='schedules'),
    path('contactus/', views.contactus, name='contactus'),
    path('signup/', views.signup, name='signup'),
    path('register/', views.register, name='register'),
    path('logout/', LogoutView.as_view(),{'next_page': settings.LOGOUT_REDIRECT_URL},name='logout'),

]

back_end/main/models.py
from django.db import models
from django.urls import reverse


class Articles(models.Model):
    name = models.CharField('name', max_length=50, db_index=True)
    email = models.CharField('email', max_length=250)
    subject = models.CharField('subject', max_length=250)
    message = models.TextField('message')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Message'
        verbose_name_plural = 'Messages'

back_end/main/forms.py
from .models import Articles
#  Product
from django.forms import ModelForm, TextInput, Textarea, NumberInput
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class ArticlesForm(ModelForm):
    class Meta:
        model = Articles
        fields = ['name', 'email', 'subject', 'message']

        widgets = {
            'name': TextInput(attrs={
                'placeholder': "Your Name*",

            }),
            'email': TextInput(attrs={
                'placeholder': "Your Email*",

            }),
            'subject': TextInput(attrs={
                'placeholder': "Subject",

            }),
            'message': Textarea(attrs={
                'placeholder': "Message",
            })
        }


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

back_end/main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ArticlesForm, CreateUserForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
# from .models import Category, Product


def index(request):
    return render(request, 'main/index.html')


def about(request):
    return render(request, 'main/about.html')



def classes(request):
    return render(request, 'main/classes.html')


def contactus(request):
    error = ''
    if request.method == 'POST':
        form = ArticlesForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("{% url 'contactus'%}")
        else:
            error = 'ERROR'

    form = ArticlesForm()

    data = {
        'form': form,
        'error': error
    }
    return render(request, 'main/contactus.html', data)


def schedules(request):
    return render(request, 'main/schedules.html')


def signup(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            messages.info(request, 'Username or password incorrect')

    context = {}
    return render(request, 'main/signup.html', context)


def register(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'Account was created for ' + user)

            return redirect("{% url 'signup'%}")
    context = {'form': form}

    return render(request, 'main/register.html', context)


def logout(request):
    logout(request)

back_end/main/templates/main/about.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/83a628d2b5.js" crossorigin="anonymous"></script>
    <title>Training Studio - Free CSS Template</title>
    <link rel="stylesheet" href="{% static 'main/css/about.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/bootstrap.min.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'main/css/font-awesome.css' %}">

    <link rel="stylesheet" href="{% static 'main/css/templatemo-training-studio.css' %}">
    <script src="https://kit.fontawesome.com/83a628d2b5.js" crossorigin="anonymous"></script>
 </head>

<body>
  <header class="header-area header-sticky">
        <div class="container ">
            <div class="row ">
                <div class="col-12">
                    <nav class="main-nav " >
                        <!-- ***** Logo Start ***** -->
                         <a href="{% url 'home' %}" class="logo" style="color: black;">Training<em> Studio</em></a>
                        <!-- ***** Logo End ***** -->
                        <!-- ***** Menu Start ***** -->
                        <ul class="nav">
                            <li class="scroll-to-section"><a href="{% url 'home' %}" style="color: black;">Home</a></li>
                            <li class="scroll-to-section"><a href="{% url 'about' %}" class="active">About</a></li>
                            <li class="scroll-to-section"><a href="{% url 'classes' %}" style="color: black;">Classes</a></li>
                            <li class="scroll-to-section"><a href="{% url 'schedules' %}"style="color: black;">Schedules</a></li>
                            <li class="scroll-to-section"><a href="{% url 'contactus' %}"style="color: black;">Contact</a></li>
                            <li class="scroll-to-section"><a href="{% url 'abonements:product_list' %}"style="color: black;" >Prices</a></li>
                            {% if user.is_authenticated %}
                                <li><a href="{% url 'logout'%}?next={{request.path}}">{{ user.get_username }}/Logout</a></li>
                            {% else %}
                                <li><a class="main-button" href="{% url 'signup'%}?next={{request.path}}">Login</a></li>
                            {% endif %}
                        </ul>
                        <a class='menu-trigger'>
                            <span>Menu</span>
                        </a>
                        <!-- ***** Menu End ***** -->
                    </nav>
                </div>
            </div>
        </div>
    </header>

	  <section class="section" id="features">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 offset-lg-3">
                    <div class="section-heading">
                        <h2>Choose <em>Program</em></h2>
                        <img src="{% static 'main/img/line-dec.png' %}" alt="waves">
                        <p>Training Studio is free CSS template for gyms and fitness centers. You are allowed to use this layout for your business website.</p>
                    </div>
                </div>
                <div class="col-lg-6">
                    <ul class="features-items">
                        <li class="feature-item">
                            <div class="left-icon">
                                <img src="{% static 'main/img/features-first-icon.png' %}" alt="First One">
                            </div>
                            <div class="right-content">
                                <h4>Basic Fitness</h4>
                                <p>Please do not re-distribute this template ZIP file on any template collection website. This is not allowed.</p>
                                <a href="#" class="text-button">Discover More</a>
                            </div>
                        </li>
                        <li class="feature-item">
                            <div class="left-icon">
                                <img src="{% static 'main/img/features-first-icon.png' %}" alt="second one">
                            </div>
                            <div class="right-content">
                                <h4>New Gym Training</h4>
                                <p>If you wish to support TemplateMo website via PayPal, please feel free to contact us. We appreciate it a lot.</p>
                                <a href="#" class="text-button">Discover More</a>
                            </div>
                        </li>
                        <li class="feature-item">
                            <div class="left-icon">
                                <img src="{% static 'main/img/features-first-icon.png' %}" alt="third gym training">
                            </div>
                            <div class="right-content">
                                <h4>Basic Muscle Course</h4>
                                <p>Credit goes to <a rel="nofollow" href="https://www.pexels.com" target="_blank">Pexels website</a> for img and video background used in this HTML template.</p>
                                <a href="#" class="text-button">Discover More</a>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="col-lg-6">
                    <ul class="features-items">
                        <li class="feature-item">
                            <div class="left-icon">
                                <img src="{% static 'main/img/features-first-icon.png' %}" alt="fourth muscle">
                            </div>
                            <div class="right-content">
                                <h4>Advanced Muscle Course</h4>
                                <p>You may want to browse through <a rel="nofollow" href="https://templatemo.com/tag/digital-marketing" target="_parent">Digital Marketing</a> or <a href="https://templatemo.com/tag/corporate">Corporate</a> HTML CSS templates on our website.</p>
                                <a href="#" class="text-button">Discover More</a>
                            </div>
                        </li>
                        <li class="feature-item">
                            <div class="left-icon">
                                <img src="{% static 'main/img/features-first-icon.png' %}" alt="training fifth">
                            </div>
                            <div class="right-content">
                                <h4>Yoga Training</h4>
                                <p>This template is built on Bootstrap v4.3.1 framework. It is easy to adapt the columns and sections.</p>
                                <a href="#" class="text-button">Discover More</a>
                            </div>
                        </li>
                        <li class="feature-item">
                            <div class="left-icon">
                                <img src="{% static 'main/img/features-first-icon.png' %}" alt="gym training">
                            </div>
                            <div class="right-content">
                                <h4>Body Building Course</h4>
                                <p>Suspendisse fringilla et nisi et mattis. Curabitur sed finibus nisi. Integer nibh sapien, vehicula et auctor.</p>
                                <a href="#" class="text-button">Discover More</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </section>


</body>
<footer>
    <div class="container  ">
            <div class="row ">
                <div class="col-lg-10 offset-lg-1  ">
                    <div class="cta-content" >
                         <h2 style="color: black;">We <em> are </em> on </h2>
                    </div>
                    <div class="wr mt-5">
                         <div class="wrapper ">
                            <a href="https://www.facebook.com/profile.php?id=100076442886784" class="button">
                                <div class="icon"><i class="fab fa-facebook-f"></i></div>
                                <span>Facebook</span>
                            </a>
                        </div>

                        <div class="wrapper">
                            <a href="https://twitter.com/home" class="button">
                                <div class="icon"><i class="fab fa-twitter"></i></div>
                                <span>Twitter</span>
                            </a>
                        </div>

                        <div class="wrapper">
                            <a href="https://www.instagram.com/workoutgym.kz/" class="button">
                                <div class="icon"><i class="fab fa-instagram"></i></div>
                                <span>Instagram</span>
                            </a>
                        </div>

                        <div class="wrapper">
                            <a href="https://www.youtube.com/watch?v=sN3xlQmHSiA" class="button">
                                <div class="icon"><i class="fab fa-youtube"></i></div>
                                <span>YouTube</span>
                            </a>
                        </div>
                         <div class="main-button scroll-to-section">
                            <a href="{% url 'contactus' %}"> Call me!</a>
                        </div>
                    </div>
                                </div>
                            </div>
        </div>


    </footer>
<script src="{% static 'main/js/jquery-2.1.0.min.js' %}"></script>

    <!-- Bootstrap -->
    <script src="{% static 'main/js/popper.js' %}"></script>
    <script src="{% static 'main/js/bootstrap.min.js' %}"></script>

    <!-- Plugins -->
    <script src="{% static 'main/js/scrollreveal.min.js' %}"></script>
    <script src="{% static 'main/js/waypoints.min.js' %}"></script>
    <script src="{% static 'main/js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'main/js/imgfix.min.js' %}"></script>
    <script src="{% static 'main/js/mixitup.js' %}"></script>
    <script src="{% static 'main/js/accordions.js' %}"></script>

    <!-- Global Init -->
    <script src="{% static 'main/js/custom.js' %}"></script>

</html>

back_end/main/templates/main/classes.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap" rel="stylesheet">

    <title>Training Studio - Free CSS Template</title>

    <link rel="stylesheet" type="text/css" href="{% static 'main/css/bootstrap.min.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'main/css/font-awesome.css' %}">

    <link rel="stylesheet" href="{% static 'main/css/templatemo-training-studio.css' %}">

 </head>

<body>
  <header class="header-area header-sticky">
        <div class="container ">
            <div class="row ">
                <div class="col-12">
                    <nav class="main-nav " >
                        <!-- ***** Logo Start ***** -->
                         <a href="{% url 'home' %}" class="logo" style="color: black;" >Training<em> Studio</em></a>
                        <!-- ***** Logo End ***** -->
                        <!-- ***** Menu Start ***** -->
                        <ul class="nav">
                            <li class="scroll-to-section"><a href="{% url 'home' %}"style="color: black;">Home</a></li>
                            <li class="scroll-to-section"><a href="{% url 'about' %}"style="color: black;">About</a></li>
                            <li class="scroll-to-section"><a href="{% url 'classes' %}"class="active">Classes</a></li>
                            <li class="scroll-to-section"><a href="{% url 'schedules' %}"style="color: black;">Schedules</a></li>
                            <li class="scroll-to-section"><a href="{% url 'contactus' %}"style="color: black;">Contact</a></li>
                            <li class="scroll-to-section"><a href="{% url 'abonements:product_list' %}"style="color: black;" >Prices</a></li>
                            {% if user.is_authenticated %}
                                <li><a href="{% url 'logout'%}?next={{request.path}}">{{ user.get_username }}/Logout</a></li>
                            {% else %}
                                <li><a class="main-button" href="{% url 'signup'%}?next={{request.path}}">Login</a></li>
                            {% endif %}
                        </ul>
                        <a class='menu-trigger'>
                            <span>Menu</span>
                        </a>
                        <!-- ***** Menu End ***** -->
                    </nav>
                </div>
            </div>
        </div>
    </header>

<section class="section" id="our-classes">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 offset-lg-3">
                    <div class="section-heading">
                        <h2>Our <em>Classes</em></h2>
                        <img src="{% static 'main/img/line-dec.png' %}" alt="">
                        <p>Nunc urna sem, laoreet ut metus id, aliquet consequat magna. Sed viverra ipsum dolor, ultricies fermentum massa consequat eu.</p>
                    </div>
                </div>
            </div>
            <div class="row" id="tabs">
              <div class="col-lg-4">
                <ul>
                  <li><a href='#tabs-1'><img src="{% static 'main/img/tabs-first-icon.png' %}" alt="">First Training Class</a></li>
                  <li><a href='#tabs-2'><img src="{% static 'main/img/tabs-first-icon.png' %}" alt="">Second Training Class</a></a></li>
                  <li><a href='#tabs-3'><img src="{% static 'main/img/tabs-first-icon.png' %}" alt="">Third Training Class</a></a></li>
                  <li><a href='#tabs-4'><img src="{% static 'main/img/tabs-first-icon.png' %}" alt="">Fourth Training Class</a></a></li>
                  <div class="main-rounded-button"><a href="{% url 'schedules' %}">View All Schedules</a></div>
                </ul>
              </div>
              <div class="col-lg-8">
                <section class='tabs-content'>
                  <article id='tabs-1'>
                    <img src="{% static 'main/img/training-image-01.jpg' %}" alt="First Class">
                    <h4>First Training Class</h4>
                    <p>Phasellus convallis mauris sed elementum vulputate. Donec posuere leo sed dui eleifend hendrerit. Sed suscipit suscipit erat, sed vehicula ligula. Aliquam ut sem fermentum sem tincidunt lacinia gravida aliquam nunc. Morbi quis erat imperdiet, molestie nunc ut, accumsan diam.</p>
                    <div class="main-button">
                        <a href="{% url 'schedules' %}">View Schedule</a>
                    </div>
                  </article>
                  <article id='tabs-2'>
                    <img src="{% static 'main/img/training-image-02.jpg' %}" alt="Second Training">
                    <h4>Second Training Class</h4>
                    <p>Integer dapibus, est vel dapibus mattis, sem mauris luctus leo, ac pulvinar quam tortor a velit. Praesent ultrices erat ante, in ultricies augue ultricies faucibus. Nam tellus nibh, ullamcorper at mattis non, rhoncus sed massa. Cras quis pulvinar eros. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
                    <div class="main-button">
                        <a href="#">View Schedule</a>
                    </div>
                  </article>
                  <article id='tabs-3'>
                    <img src="{% static 'main/img/training-image-03.jpg' %}" alt="Third Class">
                    <h4>Third Training Class</h4>
                    <p>Fusce laoreet malesuada rhoncus. Donec ultricies diam tortor, id auctor neque posuere sit amet. Aliquam pharetra, augue vel cursus porta, nisi tortor vulputate sapien, id scelerisque felis magna id felis. Proin neque metus, pellentesque pharetra semper vel, accumsan a neque.</p>
                    <div class="main-button">
                        <a href="schedules.html">View Schedule</a>
                    </div>
                  </article>
                  <article id='tabs-4'>
                    <img src="{% static 'main/img/training-image-04.jpg' %}" alt="Fourth Training">
                    <h4>Fourth Training Class</h4>
                    <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean ultrices elementum odio ac tempus. Etiam eleifend orci lectus, eget venenatis ipsum commodo et.</p>
                    <div class="main-button">
                        <a href="schedules.html">View Schedule</a>
                    </div>
                  </article>
                </section>
              </div>
            </div>
        </div>
    </section>
    <section class="section" id="call-to-action">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 offset-lg-1">
                    <div class="cta-content" >
                        <h2 style="color: black;">Don’t <em>think</em>, begin <em>today</em>!</h2>
                        <p style="color: black;">Ut consectetur, metus sit amet aliquet placerat, enim est ultricies ligula, sit amet dapibus odio augue eget libero. Morbi tempus mauris a nisi luctus imperdiet.</p>
                        <div class="main-button scroll-to-section">
                            <a href="/classes">Become a member</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
<footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; 2020 Training Studio

                    - Designed by <a rel="nofollow" href="https://templatemo.com" class="tm-text-link" target="_parent">TemplateMo</a></p>

                    <!-- You shall support us a little via PayPal to info@templatemo.com -->

                </div>
            </div>
        </div>
    </footer>
<script src="{% static 'main/js/jquery-2.1.0.min.js' %}"></script>

    <!-- Bootstrap -->
    <script src="{% static 'main/js/popper.js' %}"></script>
    <script src="{% static 'main/js/bootstrap.min.js' %}"></script>

    <!-- Plugins -->
    <script src="{% static 'main/js/scrollreveal.min.js' %}"></script>
    <script src="{% static 'main/js/waypoints.min.js' %}"></script>
    <script src="{% static 'main/js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'main/js/imgfix.min.js' %}"></script>
    <script src="{% static 'main/js/mixitup.js' %}"></script>
    <script src="{% static 'main/js/accordions.js' %}"></script>

    <!-- Global Init -->
    <script src="{% static 'main/js/custom.js' %}"></script>
</html>

back_end/main/templates/main/contactus.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap" rel="stylesheet">

    <title>Training Studio - Free CSS Template</title>

    <link rel="stylesheet" type="text/css" href="{% static 'main/css/bootstrap.min.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'main/css/font-awesome.css' %}">

    <link rel="stylesheet" href="{% static 'main/css/templatemo-training-studio.css' %}">

 </head>

<body>
  <header class="header-area header-sticky">
        <div class="container ">
            <div class="row ">
                <div class="col-12">
                    <nav class="main-nav " >
                        <!-- ***** Logo Start ***** -->
                         <a href="{% url 'home' %}" class="logo" style="color: black;" >Training<em> Studio</em></a>
                        <!-- ***** Logo End ***** -->
                        <!-- ***** Menu Start ***** -->
                        <ul class="nav">
                            <li class="scroll-to-section"><a href="{% url 'home' %}"style="color: black;">Home</a></li>
                            <li class="scroll-to-section"><a href="{% url 'about' %}"style="color: black;">About</a></li>
                            <li class="scroll-to-section"><a href="{% url 'classes' %}"style="color: black;">Classes</a></li>
                            <li class="scroll-to-section"><a href="{% url 'schedules' %}"style="color: black;">Schedules</a></li>
                            <li class="scroll-to-section"><a href="{% url 'contactus' %}"class="active">Contact</a></li>
                            <li class="scroll-to-section"><a href="{% url 'abonements:product_list' %}"style="color: black;" >Prices</a></li>
                            {% if user.is_authenticated %}
                                <li><a href="{% url 'logout'%}?next={{request.path}}">{{ user.get_username }}/Logout</a></li>
                            {% else %}
                                <li><a class="main-button" href="{% url 'signup'%}?next={{request.path}}">Login</a></li>
                            {% endif %}
                        </ul>
                        <a class='menu-trigger'>
                            <span>Menu</span>
                        </a>
                        <!-- ***** Menu End ***** -->
                    </nav>
                </div>
            </div>
        </div>
    </header>
<section class="section" id="contact-us" >
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-xs-12">
                    <div id="map">
                      <iframe src="https://maps.google.com/maps?q=Av.+L%C3%BAcio+Costa,+Rio+de+Janeiro+-+RJ,+Brazil&t=&z=13&ie=UTF8&iwloc=&output=embed" width="100%" height="600px" frameborder="0" style="border:0" allowfullscreen></iframe>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-xs-12">
                    <div class="contact-form" style="background-image: url({% static 'main/img/contact-bg.jpg' %} )">
                        <form id="contact" method="post">
                            {% csrf_token %}
                            {{form.name}}
                             {{form.email}}
                             {{form.subject}}
                             {{form.message}}
                            <span>{{error}}</span>
                                <button type="submit" id="form-submit" class="main-button"> Send Message </button>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
<footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; 2020 Training Studio

                    - Designed by <a rel="nofollow" href="https://templatemo.com" class="tm-text-link" target="_parent">TemplateMo</a></p>

                    <!-- You shall support us a little via PayPal to info@templatemo.com -->

                </div>
            </div>
        </div>
    </footer>
    <script src="{% static 'main/js/jquery-2.1.0.min.js' %}"></script>

    <!-- Bootstrap -->
    <script src="{% static 'main/js/popper.js' %}"></script>
    <script src="{% static 'main/js/bootstrap.min.js' %}"></script>

    <!-- Plugins -->
    <script src="{% static 'main/js/scrollreveal.min.js' %}"></script>
    <script src="{% static 'main/js/waypoints.min.js' %}"></script>
    <script src="{% static 'main/js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'main/js/imgfix.min.js' %}"></script>
    <script src="{% static 'main/js/mixitup.js' %}"></script>
    <script src="{% static 'main/js/accordions.js' %}"></script>

    <!-- Global Init -->
    <script src="{% static 'main/js/custom.js' %}"></script>
</html>

back_end/main/templates/main/index.html
{% extends 'main/layout.html'%}
{%load static%}
{% block content %}
<div class="main-banner" id="top">
        <video autoplay muted loop id="bg-video">
            <source src=" {% static 'main/img/gym-video.mp4' %} " type="video/mp4" />
        </video>

        <div class="video-overlay header-text">
            <div class="caption">
                <h6>work harder, get stronger</h6>
                <h2>easy with our <em>gym</em></h2>
                <div class="main-button scroll-to-section">
                    <a href="/classes">Become a member</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

back_end/main/templates/main/logout.html
<p>Logged out!</p>

<a href="{% url 'signup' %}">Click here to login again.</a>